### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by mivige** [mivige/FileOrganizer#1]
- [x] Refactor the source to make it more readable

**Comment by gotocoto** [comment]
Hey! I will like to work on this!

**Comment by mivige** [comment]
> Hey! I will like to work on this!

Sure! I saw that you already created a fork, when you'll finish you can send the pull request and add me as the reviewer. Thanks!

**Comment by mivige** [comment]
> [mivige](https://github.com/mivige) merged commit [2ce4988](https://github.com/mivige/FileOrganizer/commit/2ce49883544bf5ba1e90a8859b60c1f10e57e391) into mivige:main

@gotocoto Thanks for your help!
